apiVersion: v2
name: mindweaver
description: A Helm chart for Mindweaver - Management tool for deploying data platform components on Kubernetes.
type: application
version: 0.1.1
appVersion: "0.1.1"
dependencies:
  - name: valkey
    version: 0.9.3
    repository: https://valkey.io/valkey-helm/
    condition: valkey.enabled
