[project]
name = "mindweaver_fe"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "reflex>=0.8.20",
    "httpx>=0.25.0",
    "pydantic-settings>=2.0.0"
]
