apiVersion: v1
kind: Service
metadata:
  name: mw-db-cluster-nodeport
  namespace: mindweaver-dev
spec:
  ports:
  - name: postgres
    port: 5432
    protocol: TCP
    targetPort: 5432
    nodePort: 31432
  selector:
    cnpg.io/cluster: mw-db-cluster
    cnpg.io/instanceRole: primary
  type: NodePort