resources:
  - ../base
  - db-nodeport.yml
patches:
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
      name: mw-db
    patch: |
      - op: replace
        path: /spec/destination/namespace
        value: mindweaver-dev
      - op: replace
        path: /spec/project
        value: mindweaver-dev
      - op: replace
        path: /spec/source/helm/parameters/0/value
        value: "1"