{{- if .Values.initSchema.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "hive-metastore.fullname" . }}-initschema
  labels:
    {{- include "hive-metastore.labels" . | nindent 4 }}
  {{- with .Values.initSchema.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  template:
    metadata:
      labels:
        {{- include "hive-metastore.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "hive-metastore.serviceAccountName" . }}
      restartPolicy: OnFailure
      containers:
        - name: initschema
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: ["initSchema"]
          env:
            {{- include "hive-metastore.databaseEnv" . | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /opt/conf
      volumes:
        - name: config
          configMap:
            name: {{ include "hive-metastore.fullname" . }}-config
{{- end }}
