{{- if not .Values.database.secretRef.name }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hive-metastore.fullname" . }}-db-secret
  labels:
    {{- include "hive-metastore.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.database.secretRef.hostKey }}: {{ .Values.database.host | b64enc | quote }}
  {{ .Values.database.secretRef.portKey }}: {{ .Values.database.port | toString | b64enc | quote }}
  {{ .Values.database.secretRef.dbnameKey }}: {{ .Values.database.dbname | b64enc | quote }}
  {{ .Values.database.secretRef.userKey }}: {{ .Values.database.user | b64enc | quote }}
  {{ .Values.database.secretRef.passwordKey }}: {{ .Values.database.password | b64enc | quote }}
{{- end }}
