{{- if .Values.beat.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mindweaver.fullname" . }}-beat
  labels:
    {{- include "mindweaver.labels" . | nindent 4 }}
    app.kubernetes.io/component: beat
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "mindweaver.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: beat
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "mindweaver.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: beat
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "mindweaver.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-beat
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["celery"]
          args: ["-A", "mindweaver.celery_app", "beat", "-l", "info"]
          resources:
            {{- toYaml .Values.beat.resources | nindent 12 }}
          {{- if .Values.postgresql.enabled }}
          env:
            - name: MINDWEAVER_DB_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ include "mindweaver.fullname" . }}-db-app
                  key: host
            - name: MINDWEAVER_DB_PORT
              valueFrom:
                secretKeyRef:
                  name: {{ include "mindweaver.fullname" . }}-db-app
                  key: port
            - name: MINDWEAVER_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "mindweaver.fullname" . }}-db-app
                  key: dbname
            - name: MINDWEAVER_DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "mindweaver.fullname" . }}-db-app
                  key: user
            - name: MINDWEAVER_DB_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ include "mindweaver.fullname" . }}-db-app
                  key: password
          {{- end }}
          envFrom:
            - configMapRef:
                name: {{ include "mindweaver.fullname" . }}-config
            - secretRef:
                name: {{ include "mindweaver.fullname" . }}-secret
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
