{{- if .Values.postgresql.enabled -}}
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ include "mindweaver.fullname" . }}-db
  labels:
    {{- include "mindweaver.labels" . | nindent 4 }}
spec:
  instances: {{ .Values.postgresql.instances }}

  # Example of how to configure storage
  storage:
    size: {{ .Values.postgresql.storage.size }}

{{- end }}
