{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "mindweaver.fullname" . }}-role
  labels:
    {{- include "mindweaver.labels" . | nindent 4 }}
rules:
  # Allow access to all namespaced resources
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "mindweaver.fullname" . }}-rolebinding
  labels:
    {{- include "mindweaver.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "mindweaver.fullname" . }}-role
subjects:
  - kind: ServiceAccount
    name: {{ include "mindweaver.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end -}}
