apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mindweaver.fullname" . }}-secret
  labels:
    {{- include "mindweaver.labels" . | nindent 4 }}
type: Opaque
data:
  MINDWEAVER_JWT_SECRET: {{ .Values.secret.jwtSecret | b64enc | quote }}
  {{- if .Values.secret.fernetKey }}
  MINDWEAVER_FERNET_KEY: {{ .Values.secret.fernetKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.secret.oidc.issuer }}
  MINDWEAVER_OIDC_ISSUER: {{ .Values.secret.oidc.issuer | b64enc | quote }}
  {{- end }}
  {{- if .Values.secret.oidc.clientId }}
  MINDWEAVER_OIDC_CLIENT_ID: {{ .Values.secret.oidc.clientId | b64enc | quote }}
  {{- end }}
  {{- if .Values.secret.oidc.clientSecret }}
  MINDWEAVER_OIDC_CLIENT_SECRET: {{ .Values.secret.oidc.clientSecret | b64enc | quote }}
  {{- end }}
