apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mw-db
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
spec:
  project: mindweaver

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground

  destination:
    server: https://kubernetes.default.svc
    namespace: mindweaver

  source:
    repoURL: https://cloudnative-pg.github.io/charts
    chart: cluster
    targetRevision: 0.3.1

    helm:
      parameters:
        - name: "cluster.instances"
          value: "3"

      values: |
          version:
            postgresql: "16"
         
          mode: "standalone"
          cluster:
            enableSuperuserAccess: true