apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: mindweaver
  namespace: argocd
spec:
  description: Mindweaver
  sourceRepos:
    - '*'
  destinations:
    - namespace: 'mindweaver'
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceBlacklist:
    - group: "argoproj.io"
      kind: "AppProject"
  orphanedResources:
    warn: false