name: Build Hive Metastore Image

on:
  push:
    branches:
      - main
    paths:
      - "images/hive-metastore/**"
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build-hms-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Download external dependencies
        run: |
          cd images/hive-metastore
          chmod +x download.sh
          ./download.sh

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract version and timestamp
        run: |
          echo "VERSION=$(cat images/hive-metastore/VERSION.txt)" >> $GITHUB_ENV
          echo "TIMESTAMP=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV

      - name: Build and push Hive Metastore image
        uses: docker/build-push-action@v5
        with:
          context: images/hive-metastore
          file: images/hive-metastore/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/mindweaver/hive-metastore:edge
            ghcr.io/${{ github.repository_owner }}/mindweaver/hive-metastore:${{ github.sha }}
            ghcr.io/${{ github.repository_owner }}/mindweaver/hive-metastore:${{ env.VERSION }}-alpha.${{ env.TIMESTAMP }}

          cache-from: type=gha
          cache-to: type=gha,mode=max
